name: Test Docker Container in Actions

on:
  push:
  workflow_dispatch:

jobs:
  do_docker_stuff:
    runs-on: ubuntu-latest
    container: debian:bullseye-slim

    steps:
    - uses: actions/checkout@v2

    - name: Run Command inside Docker Container
      run: |
        ls -alh /__w/
        env
        ls -alh $GITHUB_WORKSPACE
        cat $GITHUB_WORKSPACE/README.md | tr -d 'aeiou' > $RUNNER_WORKSPACE/out.txt

  do_stuff_after_docker:
    runs-on: ubuntu-latest
    needs: do_docker_stuff
    steps:
    - name: Process output file
      run: |
        ls -alh
        cat out.txt
        
      
