name: Test Docker Container in Actions

on:
  push:
  workflow_dispatch:

jobs:
  do_stuff_before_docker:
    runs-on: ubuntu-latest
    steps:
    - name: Make volume for docker
      run: |
        mkdir /containeroutput
        

  do_docker_stuff:
    runs-on: ubuntu-latest
    needs: do_stuff_before_docker
    container: 
      image: debian:bullseye-slim
      volumes:
        - /containeroutput:/output
        
    steps:
    - uses: actions/checkout@v2

    - name: Run Command inside Docker Container
      run: |
        ls -alh /__w/
        env
        ls -alh $GITHUB_WORKSPACE
        cat $GITHUB_WORKSPACE/README.md | tr -d 'aeiou' > /output/out.txt

  do_stuff_after_docker:
    runs-on: ubuntu-latest
    needs: do_docker_stuff
    steps:
    - name: Process output file
      run: |
        pwd
        ls -alh
        ls -alh /
        ls -alh /containeroutput
        cat /containeroutput/out.txt
        
      
