name: Test Docker Container in Actions

on:
  push:
  workflow_dispatch:

jobs:
  do_docker_stuff:
    runs-on: ubuntu-latest
    container: debian:bullseye-slim

    steps:
    - uses: actions/checkout@v2

    - name: Run Command inside Docker Container
      run: |
        ls -alh /__w/
        env
